<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="87112" started-at="2020-07-22T03:15:46Z" finished-at="2020-07-22T03:17:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="87112" started-at="2020-07-22T03:15:46Z" finished-at="2020-07-22T03:17:13Z">
      <class name="com.jbk.LoginWithPoi">
        <test-method status="PASS" signature="readTest()[pri:0, instance:com.jbk.LoginWithPoi@523884b2]" name="readTest" is-config="true" duration-ms="882" started-at="2020-07-22T03:15:46Z" finished-at="2020-07-22T03:15:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readTest -->
        <test-method status="FAIL" signature="test01()[pri:0, instance:com.jbk.LoginWithPoi@523884b2]" name="test01" duration-ms="86017" started-at="2020-07-22T03:15:47Z" finished-at="2020-07-22T03:17:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.jbk.LoginWithPoi.test01(LoginWithPoi.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test01 -->
        <test-method status="PASS" signature="writeExcel()[pri:0, instance:com.jbk.LoginWithPoi@523884b2]" name="writeExcel" is-config="true" duration-ms="151" started-at="2020-07-22T03:17:13Z" finished-at="2020-07-22T03:17:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeExcel -->
      </class> <!-- com.jbk.LoginWithPoi -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
